# Deploy progressively with canary stragegy.
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
    kustomizeVersion: 3.5.5
  pipeline:
    stages:
      # Deploy the workloads of CANARY variant. In this case, the number of
      # workload replicas of CANARY variant is 10% of the replicas number of PRIMARY variant.
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 50%
      - name: WAIT_APPROVAL
        with:
          approvers:
            - jaganikuman
      - name: K8S_TRAFFIC_ROUTING
        with:
          primary: 0
          canary: 100
      - name: WAIT_APPROVAL
        with:
          approvers:
            - jaganikuman
      # Update the workload of PRIMARY variant to the new version.
      - name: K8S_PRIMARY_ROLLOUT
      - name: WAIT_APPROVAL
        with:
          approvers:
            - jaganikuman
      - name: K8S_TRAFFIC_ROUTING
        with:
          primary: 100
          canary: 0
      # Destroy all workloads of CANARY variant.
      - name: K8S_CANARY_CLEAN
